<ul class="list-group list-group-flush offcanvas-body">
    <li class="list-group-item list-group-item-action">An item</li>
    <li class="list-group-item list-group-item-action">A second item</li>
    <li class="list-group-item list-group-item-action">A third item</li>
    <li class="list-group-item list-group-item-action">A fourth item</li>
    <li class="list-group-item list-group-item-action">And a fifth one</li>
    <li class="list-group-item list-group-item-action">An item</li>
    <li class="list-group-item list-group-item-action">A second item</li>
    <li class="list-group-item list-group-item-action">A third item</li>
    <li class="list-group-item list-group-item-action">A fourth item</li>
    <li class="list-group-item list-group-item-action">And a fifth one</li>
    <li class="list-group-item list-group-item-action">An item</li>
    <li class="list-group-item list-group-item-action">A second item</li>
    <li class="list-group-item list-group-item-action">A third item</li>
    <li class="list-group-item list-group-item-action">A fourth item</li>
    <li class="list-group-item list-group-item-action">And a fifth one</li>
    <li class="list-group-item list-group-item-action">An item</li>
    <li class="list-group-item list-group-item-action">A second item</li>
    <li class="list-group-item list-group-item-action">A third item</li>
    <li class="list-group-item list-group-item-action">A fourth item</li>
    <li class="list-group-item list-group-item-action">And a fifth one</li>
    <li class="list-group-item list-group-item-action">An item</li>
    <li class="list-group-item list-group-item-action">A second item</li>
    <li class="list-group-item list-group-item-action">A third item</li>
    <li class="list-group-item list-group-item-action">A fourth item</li>
    <li class="list-group-item list-group-item-action">And a fifth one</li>
    <li class="list-group-item list-group-item-action">An item</li>
    <li class="list-group-item list-group-item-action">A second item</li>
    <li class="list-group-item list-group-item-action">A third item</li>
    <li class="list-group-item list-group-item-action">A fourth item</li>
    <li class="list-group-item list-group-item-action">And a fifth one</li>
</ul>